### ISSUE TITLE
Variables Missing from Tracing Data

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/product-integrator-mi#4214]
### Description

With the following configuration, we can include variables in the tracing data. However, variables are currently collected only if either `stat.tracer.collect_payloads` or` stat.tracer.collect_mediation_properties` is set to true.

```toml
[mediation]
flow.statistics.capture_all = true
stat.tracer.collect_mediation_variables = true
```

### Steps to Reproduce

1. Deploy an API with tracing enabled.
2. Configure Jaeger tracing with the following settings
```toml
[mediation]
flow.statistics.capture_all = true
stat.tracer.collect_mediation_variables = true
```

### Version

4.4.0
